### ISSUE TITLE
alternative method for providing npm tokens for private packages 

### ISSUE THREAD

**Issue by ahmadnassri** [dependencies-io/actor-js-npm#21]
I get that using the `npmrc` property to set registers and thus token is the current desired approach to including private package checking, this is not necessarily a scalable or secure method of sharing tokens.

ideally, there could be an authentication with npm service side, and enable it per repo ...

**Comment by ahmadnassri** [comment]
the issue with encrypted variables is now I have to maintain that across all my repos (potentially hundreds)

**Comment by davegaeddert** [comment]
Yeah. There would be ways to re-use a single variable (like if you saved it to the billing account via a UI so all repos in that account could use it), but I think you'd still have to _use_ it in the config file somehow per-repo. So it would make it easier if the variable changed and you had to update it or something, but wouldn't do much good if you had to add or remove a variable.

Are there any other services that you use that do this in a way you like? Especially on the scalability side? I feel like all the other CI services I use just to per-repo settings for things like this and you have to use their API if you need to make changes in bulk.

**Comment by davegaeddert** [comment]
I've got the same issue with CircleCI for example. We have hundreds of repos that use 2 secret env variables for a custom deploy process. We added a little script to our new repo process to set the variables via their API. We haven't had to change anything there yet, but would have to use the API if we did...

**Comment by ahmadnassri** [comment]
looking at the Github applications example is probably the industry leader here ... where you give implicit permissions to all or specific repos .... I could see similar solution implemented here?

**Comment by davegaeddert** [comment]
And it would still be ok if you had to use the variable in each config? Something like this:
```yaml
collectors:
- type: js-npm
  path: /
  actors:
  - type: js-npm
    settings:
      npmrc: "{{ vars.our_private_npmrc }}"
```

**Comment by felixfbecker** [comment]
Encrypted variables are not that good because if the token ever expires or needs to be changed the new encrypted value needs to be committed into dependencies.yml. Older commits will still have the old version though, so when running on an older commit the build will always fail. I would prefer to be able to set these as variables in a GUI like Travis also supports and then being able to refer to them as e.g. `$NPM_TOKEN` that gets replaced.

**Comment by davegaeddert** [comment]
I'm going to close this and move the conversation here: https://github.com/dependencies-io/support/issues/14

@ahmadnassri this is not a high priority for me right now since I haven't heard back from you. We are planning to tackle it regardless, but have some other things to get through at the moment. Happy to pick it up again if/when you're interested, thanks!

**Comment by ahmadnassri** [comment]
@davegaeddert apologies! I thought I had replied to your suggestion

> And it would still be ok if you had to use the variable in each config? Something like this:

the issue here is my org has over 700+ repos, having to manage secrets in `.yml` files is simply untenable!

**Comment by davegaeddert** [comment]
Shoot! I thought it was a little weird that you never responded. Unfortunately because of that, I pushed it down the road a little bit and we haven't put any work into it since. We're working through a major update across the whole system and are getting close to being done with it. After that though, we can take this on.

I totally understand that yml in 700 repos is just too hard to manage. We'll give it some more thought, but probably what we'll do is this:
1. Load variables from the project's billing account UI (this is how you could reuse them across your org)
1. Load variables from the project UI
1. Finally, load variables from project yaml

I think going through the "billing account" will be a good solution for situations like yours. Let me know if you have any other questions -- we'll try to get to this is as soon as we can!

**Comment by ahmadnassri** [comment]
> Load variables from the project's billing account UI (this is how you could reuse them across your org)

that would be ideal.

any thoughts on timeline? my situation is getting desperate ... 700 repos now 800+ and more things are falling into technical debt, so I might have to bite the bullet and write some script to do this setup on yml files...

**Comment by davegaeddert** [comment]
@ahmadnassri can you send me an email at dave.gaeddert at dropseed.io? We just finished up all of the v2 work and put it out today, so we can probably start working on this now. It'd be good to just go over a couple of specifics to make sure we design something that will work for your (unique) situation.
